version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directories:
      - "apps/point-of-sale"
      - "apps/dashboard"
      - "lib/common"
    schedule:
      interval: "weekly"
