# This file is a template, and might need editing before it works on your project.
dockerize-master:
  # Official docker image.
  image: docker:19.03
  stage: build
  services:
    - docker:19.03-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

dockerize-uat:
  # Official docker image.
  image: docker:19.03
  stage: build
  services:
    - docker:19.03-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:uat" .
    - docker push "$CI_REGISTRY_IMAGE:uat"
  only:
    - uat
