name: "🐛 Bug Report"
description: Report a bug found while using the SudoSOS frontend.
title: "[Bug]: "
labels: ["Type: Bug", "Status: Triage"]
body:
    -   type: dropdown
        id: browsers
        attributes:
            label: What browsers are you seeing the problem on?
            multiple: true
            options:
                - Brave
                - Chrome
                - Firefox
                - Microsoft Edge
                - Safari
                - Other
    -   type: dropdown
        id: browsers
        attributes:
            label: Is this happening on the SudoSOS point of sale or on the SudoSOS dashboard?
            multiple: true
            options:
                - Point of sale
                - Dashboard
                - Both
        validations:
            required: true
    -   type: textarea
        id: current-behavior
        attributes:
            label: Current behaviour
            description: A description of what is currently happening, including screenshots and other useful information (**DO NOT INCLUDE PRIVATE INFORMATION**).
            placeholder: Currently...
        validations:
            required: true
    -   type: textarea
        id: desired-behavior
        attributes:
            label: Desired behaviour
            description: A clear description of what you think should happen.
            placeholder: In this situation, I expected ...
    -   type: textarea
        id: reproduction
        attributes:
            label: Steps to reproduce
            description: Clearly describe which steps or actions you have taken to arrive at the problem. If you have some experience with the code, please link to the specific pieces of code.
            placeholder: I did X, then Y, before arriving at Z, when ERROR ...
        validations:
            required: true
    -   type: textarea
        id: other
        attributes:
            label: Other information
            description: Any other details?

