dockerize-master:
  image: docker:19.03
  stage: build
  services:
    - docker:19.03-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - echo "VUE_APP_API_BASE='$VUE_APP_API_BASE'" >> .env
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

dockerize:
  image: docker:19.03
  stage: build
  services:
    - docker:19.03-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - echo "VUE_APP_API_BASE='$VUE_APP_API_BASE'" >> .env
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master