import { User } from '@/entities/User';
import { Transaction } from '@/entities/Transaction';

export default class fakeTransactions {
  // eslint-disable-next-line class-methods-use-this
  public static fetchTransactions(user: User): Transaction[] {
    // something like return client.fetchTransactions(user.id);

    return [{
      id: '001',
      soldToId: 'Ruben',
      authorized: 'Ruben',
      totalPrice: 28.70,
      pointOfSale: 'Bar (GEWIS)',
      activityId: '001',
      subTransactions: [{
        transactionId: '001',
        productId: '001',
        storageId: '001',
        amount: 2,
        pricePerProduct: 0.70,
      },
      {
        transactionId: '002',
        productId: '002',
        storageId: '002',
        amount: 5,
        pricePerProduct: 1.30,
      },
      {
        transactionId: '003',
        productId: '003',
        storageId: '003',
        amount: 8,
        pricePerProduct: 2.60,
      }],
      comment: 'You spent a total of €28.70',
      createdAt: new Date(),
      updatedAt: new Date(),
    } as Transaction,
      {
        id: '002',
        soldToId: 'Ruben',
        authorized: 'Pieter',
        totalPrice: 1.40,
        pointOfSale: 'Bar (GEWIS)',
        activityId: '001',
        subTransactions: [{
          transactionId: '004',
          productId: '001',
          storageId: '001',
          amount: 2,
          pricePerProduct: 0.70,
        }],
        comment: 'You spent a total of €1.40',
        createdAt: new Date(),
        updatedAt: new Date(),
      } as Transaction,
      {
        id: '003',
        soldToId: 'Ruben',
        authorized: 'BAC',
        totalPrice: 30.00,
        pointOfSale: 'Bar (GEWIS)',
        activityId: '002',
        subTransactions: [{
          transactionId: '005',
          productId: '000',
          storageId: '000',
          amount: 1,
          pricePerProduct: 30.00,
        }],
        comment: 'You put €30.00 on your account',
        createdAt: new Date('February 2, 2020 05:07:00'),
        updatedAt: new Date(),
      } as Transaction,
      {
        id: '004',
        soldToId: 'Pieter',
        authorized: 'Ruben',
        totalPrice: 8.40,
        pointOfSale: 'Bar (GEWIS)',
        activityId: '003',
        subTransactions: [{
          transactionId: '006',
          productId: '001',
          storageId: '001',
          amount: 12,
          pricePerProduct: 0.70,
        }],
        comment: 'You spent a total of €8.40',
        createdAt: new Date('January 1, 2020 01:07:00'),
        updatedAt: new Date(),
      } as Transaction,
      {
        id: '005',
        soldToId: 'Pieter',
        authorized: 'Ruben',
        totalPrice: 8.40,
        pointOfSale: 'Bar (GEWIS)',
        activityId: '004',
        subTransactions: [{
          transactionId: '007',
          productId: '001',
          storageId: '001',
          amount: 12,
          pricePerProduct: 0.70,
        }],
        comment: 'You spent a total of €8.40',
        createdAt: new Date('December 12, 2019 00:00:00'),
        updatedAt: new Date(),
      } as Transaction,
      {
        id: '006',
        soldToId: 'Ruben',
        authorized: 'BAC',
        totalPrice: 3.80,
        pointOfSale: 'Bar (GEWIS)',
        activityId: '005',
        subTransactions: [{
          transactionId: '008',
          productId: '004',
          storageId: '001',
          amount: 2,
          pricePerProduct: 1.90,
        }],
        comment: 'You spent a total of €3.80',
        createdAt: new Date('December 5, 2019 18:00:00'),
        updatedAt: new Date(),
      } as Transaction,
      {
        id: '007',
        soldToId: 'Ruben',
        authorized: 'BAC',
        totalPrice: 38.00,
        pointOfSale: 'Bar (GEWIS)',
        activityId: '005',
        subTransactions: [{
          transactionId: '009',
          productId: '000',
          storageId: '000',
          amount: 1,
          pricePerProduct: 38.00,
        }],
        comment: 'You put €38.00 on your account',
        createdAt: new Date('December 5, 2019 17:00:00'),
        updatedAt: new Date(),
      } as Transaction,
      {
        id: '008',
        soldToId: 'Ruben',
        authorized: 'BAC',
        totalPrice: 7.60,
        pointOfSale: 'Bar (GEWIS)',
        activityId: '005',
        subTransactions: [{
          transactionId: '010',
          productId: '004',
          storageId: '001',
          amount: 4,
          pricePerProduct: 1.90,
        }],
        comment: 'You spent a total of €7.60',
        createdAt: new Date('December 5, 2019 16:30:00'),
        updatedAt: new Date(),
      } as Transaction,
      {
        id: '009',
        soldToId: 'Ruben',
        authorized: 'BAC',
        totalPrice: 8.40,
        pointOfSale: 'Bar (GEWIS)',
        activityId: '005',
        subTransactions: [{
          transactionId: '011',
          productId: '001',
          storageId: '001',
          amount: 12,
          pricePerProduct: 0.70,
        }],
        comment: 'You spent a total of €8.40',
        createdAt: new Date('December 5, 2019 16:00:00'),
        updatedAt: new Date(),
      } as Transaction,
    ] as Transaction[];
  }
}
