import { TransactionFlag, FlagStatus } from '@/entities/TransactionFlag';
import { User } from '@/entities/User';

export default class fakeTransactionFlags {
  public static fetchTransactionFlags(user: User): TransactionFlag[] {
    // something like return client.fetchTransactionFlags(user.id);
    return [
      {
        id: '001',
        flaggedById: 'Ruben',
        status: FlagStatus.TODO,
        reason:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        createdAt: new Date(),
        updatedAt: new Date(),
        transaction: {
          id: '001',
          pointOfSale: 'pos-1',
          soldToId: 'Ruben',
          authorized: 'Ruben',
          totalPrice: 50.2,
          activityId: '001',
          subTransactions: [],
          comment: 'You spent a total of €50.20',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      },
      {
        id: '002',
        flaggedById: 'Ruben',
        status: FlagStatus.REJECTED,
        reason:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        createdAt: new Date(),
        updatedAt: new Date(),
        transaction: {
          id: '002',
          pointOfSale: 'pos-1',
          soldToId: 'Ruben',
          authorized: 'Pieter',
          totalPrice: 1.4,
          activityId: '001',
          subTransactions: [],
          comment: 'You spent a total of €1.40',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      },
      {
        id: '003',
        flaggedById: 'Pieter',
        status: FlagStatus.ACCEPTED,
        reason:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        createdAt: new Date('February 3, 2020 05:07:00'),
        updatedAt: new Date(),
        transaction: {
          id: '003',
          pointOfSale: 'pos-1',
          soldToId: 'Ruben',
          authorized: 'BAC',
          totalPrice: 30.0,
          activityId: '002',
          subTransactions: [],
          comment: 'You put €30.00 on your account',
          createdAt: new Date('February 2, 2020 05:07:00'),
          updatedAt: new Date(),
        },
      },
      {
        id: '003',
        flaggedById: 'Pieter',
        status: FlagStatus.ACCEPTED,
        reason:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        createdAt: new Date('February 3, 2020 05:07:00'),
        updatedAt: new Date(),
        transaction: {
          id: '003',
          pointOfSale: 'pos-1',
          soldToId: 'Ruben',
          authorized: 'BAC',
          totalPrice: 30.0,
          activityId: '002',
          subTransactions: [],
          comment: 'You put €30.00 on your account',
          createdAt: new Date('February 2, 2020 05:07:00'),
          updatedAt: new Date(),
        },
      },
      {
        id: '003',
        flaggedById: 'Pieter',
        status: FlagStatus.ACCEPTED,
        reason:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        createdAt: new Date('February 3, 2020 05:07:00'),
        updatedAt: new Date(),
        transaction: {
          id: '003',
          pointOfSale: 'pos-1',
          soldToId: 'Ruben',
          authorized: 'BAC',
          totalPrice: 30.0,
          activityId: '002',
          subTransactions: [],
          comment: 'You put €30.00 on your account',
          createdAt: new Date('February 2, 2020 05:07:00'),
          updatedAt: new Date(),
        },
      },
      {
        id: '003',
        flaggedById: 'Pieter',
        status: FlagStatus.ACCEPTED,
        reason:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        createdAt: new Date('February 3, 2020 05:07:00'),
        updatedAt: new Date(),
        transaction: {
          id: '003',
          pointOfSale: 'pos-1',
          soldToId: 'Ruben',
          authorized: 'BAC',
          totalPrice: 30.0,
          activityId: '002',
          subTransactions: [],
          comment: 'You put €30.00 on your account',
          createdAt: new Date('February 2, 2020 05:07:00'),
          updatedAt: new Date(),
        },
      },
      {
        id: '003',
        flaggedById: 'Pieter',
        status: FlagStatus.ACCEPTED,
        reason:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        createdAt: new Date('February 3, 2020 05:07:00'),
        updatedAt: new Date(),
        transaction: {
          id: '003',
          pointOfSale: 'pos-1',
          soldToId: 'Ruben',
          authorized: 'BAC',
          totalPrice: 30.0,
          activityId: '002',
          subTransactions: [],
          comment: 'You put €30.00 on your account',
          createdAt: new Date('February 2, 2020 05:07:00'),
          updatedAt: new Date(),
        },
      },
      {
        id: '003',
        flaggedById: 'Pieter',
        status: FlagStatus.ACCEPTED,
        reason:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        createdAt: new Date('February 3, 2020 05:07:00'),
        updatedAt: new Date(),
        transaction: {
          id: '003',
          pointOfSale: 'pos-1',
          soldToId: 'Ruben',
          authorized: 'BAC',
          totalPrice: 30.0,
          activityId: '002',
          subTransactions: [],
          comment: 'You put €30.00 on your account',
          createdAt: new Date('February 2, 2020 05:07:00'),
          updatedAt: new Date(),
        },
      },
      {
        id: '003',
        flaggedById: 'Pieter',
        status: FlagStatus.ACCEPTED,
        reason:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        createdAt: new Date('February 3, 2020 05:07:00'),
        updatedAt: new Date(),
        transaction: {
          id: '003',
          pointOfSale: 'pos-1',
          soldToId: 'Ruben',
          authorized: 'BAC',
          totalPrice: 30.0,
          activityId: '002',
          subTransactions: [],
          comment: 'You put €30.00 on your account',
          createdAt: new Date('February 2, 2020 05:07:00'),
          updatedAt: new Date(),
        },
      },
    ];
  }
}
