name: Lint and build

on:
  push:
    branches:
      - develop
  pull_request:
    branches-ignore:
      - main

jobs:
  build-and-lint:
    uses: GEWIS/actions/.github/workflows/lint-and-build-yarn.yml@v1
    with:
      node-version: '22.x'
      lint: true
      format: true
      build: true
