name: Semantic Release

on:
  workflow_dispatch:
  push:
    branches:
      - ci/semver-2

jobs:
  versioning:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node.js modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Do something when a new release is published
        run: |
          echo "New Release Version: ${{ steps.semantic.outputs.new_release_version }}"
          echo "New Release Major Version: ${{ steps.semantic.outputs.new_release_major_version }}"
          echo "New Release Minor Version: ${{ steps.semantic.outputs.new_release_minor_version }}"
          echo "New Release Patch Version: ${{ steps.semantic.outputs.new_release_patch_version }}"

      - name: Save Node.js modules to cache
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-